# Maximum number of terms to combine
min_num_terms_percentile_combinations: 5
max_num_terms_percentile_combinations: 10
max_num_query_per_term_count_percentile_combinations: 10

min_num_terms_multiple_percentile_combinations: 3
max_num_terms_multiple_percentile_combinations: 6
max_num_query_per_term_count_multiple_percentile_combinations: 5

# Mixed terms configuration
max_num_mixed_terms_with_fixed_structure: 30
max_num_mixed_terms_extended_with_fixed_structure: 30

max_num_mixed_terms_with_fixed_structure_not: 10

max_num_terms_double_expected_form: 30

max_num_terms_percentilequeries: 20

max_num_middle_exit: 30

num_elements_keywordsqueries: 10

max_num_keywordsqueries: 20

num_of_ḱws_for_multiple_pp_combinations: 5

max_num_column_name_queries: 20