# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backend/proto/lucene_connector.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'backend/proto/lucene_connector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$backend/proto/lucene_connector.proto\x12\x07\x66\x61inder\".\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0f\n\x07\x64oc_ids\x18\x02 \x03(\x05\"0\n\rQueryResponse\x12\x0f\n\x07results\x18\x01 \x03(\x05\x12\x0e\n\x06scores\x18\x02 \x03(\x02\"\x16\n\x14RecreateIndexRequest\"9\n\x15RecreateIndexResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9c\x01\n\x0fLuceneConnector\x12\x39\n\x08\x45valuate\x12\x15.fainder.QueryRequest\x1a\x16.fainder.QueryResponse\x12N\n\rRecreateIndex\x12\x1d.fainder.RecreateIndexRequest\x1a\x1e.fainder.RecreateIndexResponseB\x1c\n\x18\x64\x65.tuberlin.dima.fainderP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend.proto.lucene_connector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030de.tuberlin.dima.fainderP\001'
  _globals['_QUERYREQUEST']._serialized_start=49
  _globals['_QUERYREQUEST']._serialized_end=95
  _globals['_QUERYRESPONSE']._serialized_start=97
  _globals['_QUERYRESPONSE']._serialized_end=145
  _globals['_RECREATEINDEXREQUEST']._serialized_start=147
  _globals['_RECREATEINDEXREQUEST']._serialized_end=169
  _globals['_RECREATEINDEXRESPONSE']._serialized_start=171
  _globals['_RECREATEINDEXRESPONSE']._serialized_end=228
  _globals['_LUCENECONNECTOR']._serialized_start=231
  _globals['_LUCENECONNECTOR']._serialized_end=387
# @@protoc_insertion_point(module_scope)
