"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class QueryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUERY_FIELD_NUMBER: builtins.int
    DOC_IDS_FIELD_NUMBER: builtins.int
    query: builtins.str
    """Query expression"""
    @property
    def doc_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """List of document IDs to consider (if empty, all documents will be searched)"""

    def __init__(
        self,
        *,
        query: builtins.str = ...,
        doc_ids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["doc_ids", b"doc_ids", "query", b"query"]) -> None: ...

global___QueryRequest = QueryRequest

@typing.final
class QueryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULTS_FIELD_NUMBER: builtins.int
    SCORES_FIELD_NUMBER: builtins.int
    @property
    def results(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Document IDs that match the query sorted in order of relevance"""

    @property
    def scores(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """Relevance scores of documents"""

    def __init__(
        self,
        *,
        results: collections.abc.Iterable[builtins.int] | None = ...,
        scores: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["results", b"results", "scores", b"scores"]) -> None: ...

global___QueryResponse = QueryResponse

@typing.final
class RecreateIndexRequest(google.protobuf.message.Message):
    """Empty request as no parameters needed"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RecreateIndexRequest = RecreateIndexRequest

@typing.final
class RecreateIndexResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    """Status of the recreation"""
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "success", b"success"]) -> None: ...

global___RecreateIndexResponse = RecreateIndexResponse
