"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import backend.proto.lucene_connector_pb2
import collections.abc
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class LuceneConnectorStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Evaluate: grpc.UnaryUnaryMultiCallable[
        backend.proto.lucene_connector_pb2.QueryRequest,
        backend.proto.lucene_connector_pb2.QueryResponse,
    ]

    RecreateIndex: grpc.UnaryUnaryMultiCallable[
        backend.proto.lucene_connector_pb2.RecreateIndexRequest,
        backend.proto.lucene_connector_pb2.RecreateIndexResponse,
    ]

class LuceneConnectorAsyncStub:
    Evaluate: grpc.aio.UnaryUnaryMultiCallable[
        backend.proto.lucene_connector_pb2.QueryRequest,
        backend.proto.lucene_connector_pb2.QueryResponse,
    ]

    RecreateIndex: grpc.aio.UnaryUnaryMultiCallable[
        backend.proto.lucene_connector_pb2.RecreateIndexRequest,
        backend.proto.lucene_connector_pb2.RecreateIndexResponse,
    ]

class LuceneConnectorServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Evaluate(
        self,
        request: backend.proto.lucene_connector_pb2.QueryRequest,
        context: _ServicerContext,
    ) -> typing.Union[backend.proto.lucene_connector_pb2.QueryResponse, collections.abc.Awaitable[backend.proto.lucene_connector_pb2.QueryResponse]]: ...

    @abc.abstractmethod
    def RecreateIndex(
        self,
        request: backend.proto.lucene_connector_pb2.RecreateIndexRequest,
        context: _ServicerContext,
    ) -> typing.Union[backend.proto.lucene_connector_pb2.RecreateIndexResponse, collections.abc.Awaitable[backend.proto.lucene_connector_pb2.RecreateIndexResponse]]: ...

def add_LuceneConnectorServicer_to_server(servicer: LuceneConnectorServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
